# Generated by Django 6.0.1 on 2026-02-04 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_remove_job_company_remove_job_formations_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE profiles_profile DROP COLUMN IF EXISTS education_level;",
            reverse_sql="-- No reverse operation needed"
        ),
    ]
