# Generated by Django 6.0.1 on 2026-02-04 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_auto_20260204_2236'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE profiles_profile DROP COLUMN IF EXISTS location_preference;",
            reverse_sql="-- No reverse operation needed"
        ),
    ]
