# Generated by Django 6.0.1 on 2026-02-04 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_auto_20260204_2245'),
    ]

    operations = [
        # Supprimer toutes les colonnes obsolètes qui peuvent exister
        migrations.RunSQL(
            """
            ALTER TABLE profiles_profile DROP COLUMN IF EXISTS location_preference;
            ALTER TABLE profiles_profile DROP COLUMN IF EXISTS education_level;
            ALTER TABLE profiles_profile DROP COLUMN IF EXISTS career_goals;
            ALTER TABLE profiles_profile DROP COLUMN IF EXISTS experience_level;
            ALTER TABLE profiles_profile DROP COLUMN IF EXISTS preferred_industry;
            ALTER TABLE profiles_profile DROP COLUMN IF EXISTS salary_expectation;
            """,
            reverse_sql="-- No reverse operation needed"
        ),
    ]
