# Generated by Django 6.0.1 on 2026-02-04 22:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_auto_20260204_2250'),
        ('profiles', '0014_auto_20260204_2245'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AISearchQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_text', models.TextField(verbose_name='Texte de la requête')),
                ('search_parameters', models.JSONField(default=dict, verbose_name='Paramètres de recherche')),
                ('results_count', models.IntegerField(default=0)),
                ('execution_time', models.FloatField(verbose_name="Temps d'exécution (secondes)")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Requête de recherche IA',
                'verbose_name_plural': 'Requêtes de recherche IA',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExternalJobOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre du poste')),
                ('company_name', models.CharField(max_length=200, verbose_name="Nom de l'entreprise")),
                ('description', models.TextField(verbose_name='Description')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Localisation')),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salaire minimum')),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Salaire maximum')),
                ('source', models.CharField(choices=[('indeed', 'Indeed'), ('linkedin', 'LinkedIn'), ('glassdoor', 'Glassdoor'), ('other', 'Autre')], default='indeed', max_length=20, verbose_name='Source')),
                ('external_id', models.CharField(max_length=200, unique=True, verbose_name='ID externe')),
                ('external_url', models.URLField(verbose_name='URL externe')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('extracted_skills', models.ManyToManyField(blank=True, to='profiles.skill', verbose_name='Compétences extraites')),
            ],
            options={
                'verbose_name': 'Offre externe',
                'verbose_name_plural': 'Offres externes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AIRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_type', models.CharField(choices=[('job_to_student', 'Offre pour étudiant'), ('student_to_company', 'Étudiant pour entreprise'), ('external_job', 'Offre externe')], max_length=20)),
                ('compatibility_score', models.FloatField(verbose_name='Score de compatibilité')),
                ('skill_match_score', models.FloatField(verbose_name='Score compétences')),
                ('interest_match_score', models.FloatField(verbose_name='Score intérêts')),
                ('location_score', models.FloatField(default=0, verbose_name='Score localisation')),
                ('salary_score', models.FloatField(default=0, verbose_name='Score salaire')),
                ('ai_model_version', models.CharField(default='v1.0', max_length=50)),
                ('confidence_level', models.FloatField(verbose_name='Niveau de confiance')),
                ('reasoning', models.TextField(blank=True, verbose_name='Raisonnement IA')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.company')),
                ('job_offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='companies.joboffer')),
                ('student_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
                ('external_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.externaljoboffer')),
            ],
            options={
                'verbose_name': 'Recommandation IA',
                'verbose_name_plural': 'Recommandations IA',
                'ordering': ['-compatibility_score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProfileAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_strengths', models.JSONField(default=list, verbose_name='Forces en compétences')),
                ('skill_gaps', models.JSONField(default=list, verbose_name='Lacunes en compétences')),
                ('recommended_skills', models.JSONField(default=list, verbose_name='Compétences recommandées')),
                ('career_path_suggestions', models.JSONField(default=list, verbose_name='Suggestions de carrière')),
                ('industry_matches', models.JSONField(default=list, verbose_name='Secteurs compatibles')),
                ('profile_completeness', models.FloatField(default=0, verbose_name='Complétude du profil')),
                ('marketability_score', models.FloatField(default=0, verbose_name="Score d'employabilité")),
                ('last_analysis', models.DateTimeField(auto_now=True)),
                ('analysis_version', models.CharField(default='v1.0', max_length=20)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_analysis', to='profiles.profile')),
            ],
            options={
                'verbose_name': 'Analyse de profil IA',
                'verbose_name_plural': 'Analyses de profil IA',
            },
        ),
    ]
