# Generated by Django 6.0.1 on 2026-02-05 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0015_aisearchquery_externaljoboffer_airecommendation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CVExtraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extracted_name', models.CharField(blank=True, max_length=200, verbose_name='Nom extrait')),
                ('extracted_email', models.EmailField(blank=True, max_length=254, verbose_name='Email extrait')),
                ('extracted_phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone extrait')),
                ('extracted_location', models.CharField(blank=True, max_length=200, verbose_name='Localisation extraite')),
                ('work_experiences', models.JSONField(default=list, verbose_name='Expériences professionnelles')),
                ('extracted_educations', models.JSONField(default=list, verbose_name='Formations extraites')),
                ('extracted_skills', models.JSONField(default=list, verbose_name='Compétences extraites')),
                ('extracted_languages', models.JSONField(default=list, verbose_name='Langues extraites')),
                ('extracted_projects', models.JSONField(default=list, verbose_name='Projets extraits')),
                ('extracted_certifications', models.JSONField(default=list, verbose_name='Certifications extraites')),
                ('professional_summary', models.TextField(blank=True, verbose_name='Résumé professionnel extrait')),
                ('extraction_date', models.DateTimeField(auto_now_add=True)),
                ('extraction_method', models.CharField(default='openai_gpt', max_length=50, verbose_name="Méthode d'extraction")),
                ('extraction_confidence', models.FloatField(default=0, verbose_name="Confiance de l'extraction")),
                ('raw_text', models.TextField(blank=True, verbose_name='Texte brut extrait')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Traité')),
                ('processing_errors', models.TextField(blank=True, verbose_name='Erreurs de traitement')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cv_extraction', to='profiles.profile')),
            ],
            options={
                'verbose_name': 'Extraction de CV',
                'verbose_name_plural': 'Extractions de CV',
            },
        ),
    ]
