# Generated by Django 6.0.1 on 2026-02-05 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0016_cvextraction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aisearchquery',
            name='execution_time',
            field=models.FloatField(default=0.0, verbose_name="Temps d'exécution (secondes)"),
        ),
    ]
