# Generated by Django 6.0.1 on 2026-02-05 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0017_alter_aisearchquery_execution_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externaljoboffer',
            name='source',
            field=models.CharField(choices=[('jsearch', 'JSearch'), ('indeed', 'Indeed'), ('linkedin', 'LinkedIn'), ('glassdoor', 'Glassdoor'), ('other', 'Autre')], default='jsearch', max_length=20, verbose_name='Source'),
        ),
    ]
