# Generated by Django 6.0.1 on 2026-02-05 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0018_alter_externaljoboffer_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externaljoboffer',
            name='company_name',
            field=models.CharField(max_length=300, verbose_name="Nom de l'entreprise"),
        ),
        migrations.AlterField(
            model_name='externaljoboffer',
            name='external_id',
            field=models.CharField(max_length=300, unique=True, verbose_name='ID externe'),
        ),
        migrations.AlterField(
            model_name='externaljoboffer',
            name='location',
            field=models.CharField(blank=True, max_length=300, verbose_name='Localisation'),
        ),
        migrations.AlterField(
            model_name='externaljoboffer',
            name='title',
            field=models.CharField(max_length=500, verbose_name='Titre du poste'),
        ),
    ]
