# Generated by Django 6.0.1 on 2026-02-05 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0019_alter_externaljoboffer_company_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvextraction',
            name='extracted_location',
            field=models.CharField(blank=True, max_length=300, verbose_name='Localisation extraite'),
        ),
        migrations.AlterField(
            model_name='cvextraction',
            name='extracted_name',
            field=models.CharField(blank=True, max_length=300, verbose_name='Nom extrait'),
        ),
    ]
