# Generated by Django 6.0.1 on 2026-02-05 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0020_alter_cvextraction_extracted_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='school',
            field=models.CharField(max_length=300, verbose_name='Établissement'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='title',
            field=models.CharField(max_length=300, verbose_name='Titre de la formation'),
        ),
    ]
