# Generated by Django 6.0.1 on 2026-02-04 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_alter_company_options_alter_joboffer_options_and_more'),
    ]

    operations = [
        # Supprimer toutes les colonnes obsolètes de la table JobOffer
        migrations.RunSQL(
            """
            ALTER TABLE companies_joboffer DROP COLUMN IF EXISTS required_education_level;
            ALTER TABLE companies_joboffer DROP COLUMN IF EXISTS salary_range;
            ALTER TABLE companies_joboffer DROP COLUMN IF EXISTS experience_required;
            ALTER TABLE companies_joboffer DROP COLUMN IF EXISTS remote_work;
            ALTER TABLE companies_joboffer DROP COLUMN IF EXISTS benefits;
            ALTER TABLE companies_joboffer DROP COLUMN IF EXISTS application_deadline;
            """,
            reverse_sql="-- No reverse operation needed"
        ),
    ]
